config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :blogsadmin
  resources :contactforms

  get '/lukkari', to: 'lukkari#index'

  get '/robootti', to: 'robootti#index'

  get '/java_alkeet', to: 'java_alkeet#index'

  get '/koodikarpat_peli', to: 'koodikarpat_peli#index'

  get '/grafiikka', to: 'grafiikka#index'

  get 'welcome/homepage'

  root 'welcome#homepage'

end

app/controllers/-blogsadmin_controller.rb
class BlogsadminController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "8sX6ucRQKh"
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to "/blogsadmin/", notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to "/blogsadmin/", notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.where(id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:project, :name, :posted, :subject, :content)
    end
end

app/controllers/blogsadmin_controller.rb
class BlogsadminController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "8sX6ucRQKh"
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to "/blogsadmin/", notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to "/blogsadmin/", notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.where(id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:project, :name, :posted, :subject, :content)
    end
end

app/views/blogsadmin/_form.html.erb
<%= form_for(@blog, url: "/blogsadmin/2") do |f| %>
 <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project %><br>
    <%= f.select :project, options_for_select([['Koodikarpät-peli',1],['Java-alkeet',2], ['Lukkari',3],['Robootti',4]]), required: true%>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject, required: true %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, size: "80x25", required: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogsadmin/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogsadmin/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Name</th>
      <th>Posted</th>
      <th>Subject</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.project %></td>
        <td><%= blog.name %></td>
        <td><%= blog.created_at %></td>
        <td><%= blog.subject %></td>
        <td><%= blog.content %></td>
        <td><a href="<%= blog.id %>/edit">Edit</a></td>
        <td><%= button_to "Destroy", "#{blog.id}", :method=>:delete, :class=>:destroy %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>(normal user)

app/views/blogsadmin/show.html.erb
<p id="notice"><%= notice %></p>

<% @blog.each do |blog| %>
<div class="row">
                <div class="postwrapper">
                    <div class="col-sm-3 postinfo">
                        <div class="team-member">
                            <img src="assets/koodikarpat.png" class="img-responsive img-circle" alt="Avatar">
                            <h3><%= blog.name %></h3>
                            <p class="postdate"><%= blog.created_at %></p>
                        </div>
                    </div>
                    <div class="col-sm-9 bg-light-gray postcontent">
                    <h3><%= blog.subject %></h3>
                    <%= simple_format(blog.content) %>
                    </div>
                </div>

            </div>
<% end %>
<a href="http://koodikarpat.com/">Tarkista viestisi Koodikarpat.com-projektisivulla</a>